### ISSUE TITLE
Using 40x64 image instead of 64x64 size 

### ISSUE THREAD

**Issue by daeunni** [tsunghan-wu/SLD#7]
Hi, thanks for your nice work! 
BTW, I encountered the error below: 
```
----- Image Manipulation -----
100%|█████████████████████████████████████████████████████████████████████████████████████| 50/50 [00:04<00:00, 12.23it/s]
Traceback (most recent call last):
  File "/nas-ssd2/daeun/SLD/SLD_demo.py", line 364, in <module>
    ret_dict = correction(
  File "/nas-ssd2/daeun/SLD/SLD_demo.py", line 178, in correction
    ret_dict = image_generator.run(
  File "/nas-ssd2/daeun/SLD/sld/image_generator.py", line 618, in run
    composed_latents[frozen_mask_expanded == 0] = latents_bg[
IndexError: The shape of the mask [51, 1, 4, 40, 64] at index 3 does not match the shape of the indexed tensor [51, 1, 4, 64, 64] at index 3
```

My image size was 320x512, can I implement this code in various image sizes? 
That means, is SLD input size fixed? 

Thanks!

**Comment by tsunghan-wu** [comment]
Sorry our repo doesn't support various image sizes ;(
